/**
 * Runtime types for the GainHub API Worker.
 * `Cloudflare.Env` is generated by `npm run cf:typegen` (wrangler types).
 */
export type Env = Cloudflare.Env;

export type AppContext = {
  request: Request;
  env: Env;
  execution: ExecutionContext;
  url: URL;
  requestId: string;
  /** Stable per-IP hash used for abuse signalling only — never the IP itself. */
  ipHash: string | null;
  params: Record<string, string>;
  session: import("./auth.ts").SessionInfo | null;
  log: (level: "info" | "warn" | "error", event: string, fields?: Record<string, unknown>) => void;
};

export type RouteHandler = (c: AppContext) => Promise<Response> | Response;

export type DbRow = Record<string, unknown>;
