/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as HelpRouteImport } from './routes/help'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuggestBusinessRouteImport } from './routes/suggest-business'
import { Route as TrustSafetyRouteImport } from './routes/trust-safety'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as BusinessIdRouteImport } from './routes/business.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ContactGainIndexRouteImport } from './routes/contact-gain.index'
import { Route as ContactGainIdRouteImport } from './routes/contact-gain.$id'
import { Route as ContactGainCreateRouteImport } from './routes/contact-gain.create'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalDataRequestRouteImport } from './routes/legal.data-request'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as AppBusinessesIndexRouteImport } from './routes/app/businesses.index'
import { Route as AppBusinessesIdRouteImport } from './routes/app/businesses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestBusinessRoute = SuggestBusinessRouteImport.update({
  id: '/suggest-business',
  path: '/suggest-business',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustSafetyRoute = TrustSafetyRouteImport.update({
  id: '/trust-safety',
  path: '/trust-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactGainIndexRoute = ContactGainIndexRouteImport.update({
  id: '/contact-gain/',
  path: '/contact-gain/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactGainIdRoute = ContactGainIdRouteImport.update({
  id: '/contact-gain/$id',
  path: '/contact-gain/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactGainCreateRoute = ContactGainCreateRouteImport.update({
  id: '/contact-gain/create',
  path: '/contact-gain/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDataRequestRoute = LegalDataRequestRouteImport.update({
  id: '/legal/data-request',
  path: '/legal/data-request',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocationsRoute,
} as any)
const AppBusinessesIndexRoute = AppBusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBusinessesIdRoute = AppBusinessesIdRouteImport.update({
  id: '/businesses/$id',
  path: '/businesses/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/claim': typeof ClaimRoute
  '/compare': typeof CompareRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/locations': typeof LocationsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggest-business': typeof SuggestBusinessRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/api/$': typeof ApiSplatRoute
  '/business/$id': typeof BusinessIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/contact-gain/$id': typeof ContactGainIdRoute
  '/contact-gain/create': typeof ContactGainCreateRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/data-request': typeof LegalDataRequestRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/contact-gain/': typeof ContactGainIndexRoute
  '/app/businesses/$id': typeof AppBusinessesIdRoute
  '/app/businesses/': typeof AppBusinessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/claim': typeof ClaimRoute
  '/compare': typeof CompareRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/locations': typeof LocationsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggest-business': typeof SuggestBusinessRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/api/$': typeof ApiSplatRoute
  '/business/$id': typeof BusinessIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/contact-gain/$id': typeof ContactGainIdRoute
  '/contact-gain/create': typeof ContactGainCreateRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/data-request': typeof LegalDataRequestRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/contact-gain': typeof ContactGainIndexRoute
  '/app/businesses/$id': typeof AppBusinessesIdRoute
  '/app/businesses': typeof AppBusinessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/claim': typeof ClaimRoute
  '/compare': typeof CompareRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/locations': typeof LocationsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggest-business': typeof SuggestBusinessRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/api/$': typeof ApiSplatRoute
  '/business/$id': typeof BusinessIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/contact-gain/$id': typeof ContactGainIdRoute
  '/contact-gain/create': typeof ContactGainCreateRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/data-request': typeof LegalDataRequestRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/contact-gain/': typeof ContactGainIndexRoute
  '/app/businesses/$id': typeof AppBusinessesIdRoute
  '/app/businesses/': typeof AppBusinessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/about'
    | '/account'
    | '/advertise'
    | '/auth'
    | '/categories'
    | '/claim'
    | '/compare'
    | '/help'
    | '/join'
    | '/locations'
    | '/pricing'
    | '/report'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/suggest-business'
    | '/trust-safety'
    | '/api/$'
    | '/business/$id'
    | '/category/$slug'
    | '/contact-gain/$id'
    | '/contact-gain/create'
    | '/legal/cookies'
    | '/legal/data-request'
    | '/legal/privacy'
    | '/legal/terms'
    | '/locations/$slug'
    | '/admin/'
    | '/app/'
    | '/contact-gain/'
    | '/app/businesses/$id'
    | '/app/businesses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/advertise'
    | '/auth'
    | '/categories'
    | '/claim'
    | '/compare'
    | '/help'
    | '/join'
    | '/locations'
    | '/pricing'
    | '/report'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/suggest-business'
    | '/trust-safety'
    | '/api/$'
    | '/business/$id'
    | '/category/$slug'
    | '/contact-gain/$id'
    | '/contact-gain/create'
    | '/legal/cookies'
    | '/legal/data-request'
    | '/legal/privacy'
    | '/legal/terms'
    | '/locations/$slug'
    | '/admin'
    | '/app'
    | '/contact-gain'
    | '/app/businesses/$id'
    | '/app/businesses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/about'
    | '/account'
    | '/advertise'
    | '/auth'
    | '/categories'
    | '/claim'
    | '/compare'
    | '/help'
    | '/join'
    | '/locations'
    | '/pricing'
    | '/report'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/suggest-business'
    | '/trust-safety'
    | '/api/$'
    | '/business/$id'
    | '/category/$slug'
    | '/contact-gain/$id'
    | '/contact-gain/create'
    | '/legal/cookies'
    | '/legal/data-request'
    | '/legal/privacy'
    | '/legal/terms'
    | '/locations/$slug'
    | '/admin/'
    | '/app/'
    | '/contact-gain/'
    | '/app/businesses/$id'
    | '/app/businesses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  ClaimRoute: typeof ClaimRoute
  CompareRoute: typeof CompareRoute
  HelpRoute: typeof HelpRoute
  JoinRoute: typeof JoinRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  PricingRoute: typeof PricingRoute
  ReportRoute: typeof ReportRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuggestBusinessRoute: typeof SuggestBusinessRoute
  TrustSafetyRoute: typeof TrustSafetyRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BusinessIdRoute: typeof BusinessIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ContactGainIdRoute: typeof ContactGainIdRoute
  ContactGainCreateRoute: typeof ContactGainCreateRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDataRequestRoute: typeof LegalDataRequestRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ContactGainIndexRoute: typeof ContactGainIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggest-business': {
      id: '/suggest-business'
      path: '/suggest-business'
      fullPath: '/suggest-business'
      preLoaderRoute: typeof SuggestBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-safety': {
      id: '/trust-safety'
      path: '/trust-safety'
      fullPath: '/trust-safety'
      preLoaderRoute: typeof TrustSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-gain/': {
      id: '/contact-gain/'
      path: '/contact-gain'
      fullPath: '/contact-gain/'
      preLoaderRoute: typeof ContactGainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-gain/$id': {
      id: '/contact-gain/$id'
      path: '/contact-gain/$id'
      fullPath: '/contact-gain/$id'
      preLoaderRoute: typeof ContactGainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-gain/create': {
      id: '/contact-gain/create'
      path: '/contact-gain/create'
      fullPath: '/contact-gain/create'
      preLoaderRoute: typeof ContactGainCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/data-request': {
      id: '/legal/data-request'
      path: '/legal/data-request'
      fullPath: '/legal/data-request'
      preLoaderRoute: typeof LegalDataRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/app/businesses/': {
      id: '/app/businesses/'
      path: '/businesses'
      fullPath: '/app/businesses/'
      preLoaderRoute: typeof AppBusinessesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/businesses/$id': {
      id: '/app/businesses/$id'
      path: '/businesses/$id'
      fullPath: '/app/businesses/$id'
      preLoaderRoute: typeof AppBusinessesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppBusinessesIdRoute: typeof AppBusinessesIdRoute
  AppBusinessesIndexRoute: typeof AppBusinessesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppBusinessesIdRoute: AppBusinessesIdRoute,
  AppBusinessesIndexRoute: AppBusinessesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LocationsRouteChildren {
  LocationsSlugRoute: typeof LocationsSlugRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsSlugRoute: LocationsSlugRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdvertiseRoute: AdvertiseRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  ClaimRoute: ClaimRoute,
  CompareRoute: CompareRoute,
  HelpRoute: HelpRoute,
  JoinRoute: JoinRoute,
  LocationsRoute: LocationsRouteWithChildren,
  PricingRoute: PricingRoute,
  ReportRoute: ReportRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuggestBusinessRoute: SuggestBusinessRoute,
  TrustSafetyRoute: TrustSafetyRoute,
  ApiSplatRoute: ApiSplatRoute,
  BusinessIdRoute: BusinessIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  ContactGainIdRoute: ContactGainIdRoute,
  ContactGainCreateRoute: ContactGainCreateRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDataRequestRoute: LegalDataRequestRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ContactGainIndexRoute: ContactGainIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
