/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SuggestBusinessRouteImport } from './routes/suggest-business'
import { Route as BusinessIdRouteImport } from './routes/business.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ContactGainIndexRouteImport } from './routes/contact-gain.index'
import { Route as ContactGainIdRouteImport } from './routes/contact-gain.$id'
import { Route as ContactGainCreateRouteImport } from './routes/contact-gain.create'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestBusinessRoute = SuggestBusinessRouteImport.update({
  id: '/suggest-business',
  path: '/suggest-business',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactGainIndexRoute = ContactGainIndexRouteImport.update({
  id: '/contact-gain/',
  path: '/contact-gain/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactGainIdRoute = ContactGainIdRouteImport.update({
  id: '/contact-gain/$id',
  path: '/contact-gain/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactGainCreateRoute = ContactGainCreateRouteImport.update({
  id: '/contact-gain/create',
  path: '/contact-gain/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/claim': typeof ClaimRoute
  '/join': typeof JoinRoute
  '/locations': typeof LocationsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/suggest-business': typeof SuggestBusinessRoute
  '/business/$id': typeof BusinessIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/contact-gain/$id': typeof ContactGainIdRoute
  '/contact-gain/create': typeof ContactGainCreateRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/contact-gain/': typeof ContactGainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/claim': typeof ClaimRoute
  '/join': typeof JoinRoute
  '/locations': typeof LocationsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/suggest-business': typeof SuggestBusinessRoute
  '/business/$id': typeof BusinessIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/contact-gain/$id': typeof ContactGainIdRoute
  '/contact-gain/create': typeof ContactGainCreateRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/contact-gain': typeof ContactGainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/claim': typeof ClaimRoute
  '/join': typeof JoinRoute
  '/locations': typeof LocationsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/suggest-business': typeof SuggestBusinessRoute
  '/business/$id': typeof BusinessIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/contact-gain/$id': typeof ContactGainIdRoute
  '/contact-gain/create': typeof ContactGainCreateRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/contact-gain/': typeof ContactGainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/claim'
    | '/join'
    | '/locations'
    | '/pricing'
    | '/search'
    | '/suggest-business'
    | '/business/$id'
    | '/category/$slug'
    | '/contact-gain/$id'
    | '/contact-gain/create'
    | '/locations/$slug'
    | '/contact-gain/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/claim'
    | '/join'
    | '/locations'
    | '/pricing'
    | '/search'
    | '/suggest-business'
    | '/business/$id'
    | '/category/$slug'
    | '/contact-gain/$id'
    | '/contact-gain/create'
    | '/locations/$slug'
    | '/contact-gain'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/claim'
    | '/join'
    | '/locations'
    | '/pricing'
    | '/search'
    | '/suggest-business'
    | '/business/$id'
    | '/category/$slug'
    | '/contact-gain/$id'
    | '/contact-gain/create'
    | '/locations/$slug'
    | '/contact-gain/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  ClaimRoute: typeof ClaimRoute
  JoinRoute: typeof JoinRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  PricingRoute: typeof PricingRoute
  SearchRoute: typeof SearchRoute
  SuggestBusinessRoute: typeof SuggestBusinessRoute
  BusinessIdRoute: typeof BusinessIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ContactGainIdRoute: typeof ContactGainIdRoute
  ContactGainCreateRoute: typeof ContactGainCreateRoute
  ContactGainIndexRoute: typeof ContactGainIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggest-business': {
      id: '/suggest-business'
      path: '/suggest-business'
      fullPath: '/suggest-business'
      preLoaderRoute: typeof SuggestBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-gain/': {
      id: '/contact-gain/'
      path: '/contact-gain'
      fullPath: '/contact-gain/'
      preLoaderRoute: typeof ContactGainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-gain/$id': {
      id: '/contact-gain/$id'
      path: '/contact-gain/$id'
      fullPath: '/contact-gain/$id'
      preLoaderRoute: typeof ContactGainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-gain/create': {
      id: '/contact-gain/create'
      path: '/contact-gain/create'
      fullPath: '/contact-gain/create'
      preLoaderRoute: typeof ContactGainCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof LocationsRoute
    }
  }
}

interface LocationsRouteChildren {
  LocationsSlugRoute: typeof LocationsSlugRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsSlugRoute: LocationsSlugRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  ClaimRoute: ClaimRoute,
  JoinRoute: JoinRoute,
  LocationsRoute: LocationsRouteWithChildren,
  PricingRoute: PricingRoute,
  SearchRoute: SearchRoute,
  SuggestBusinessRoute: SuggestBusinessRoute,
  BusinessIdRoute: BusinessIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  ContactGainIdRoute: ContactGainIdRoute,
  ContactGainCreateRoute: ContactGainCreateRoute,
  ContactGainIndexRoute: ContactGainIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
